export const FILL_CELL = 'FILL_CELL';
export const TOGGLE_DRAGGING = 'TOGGLE_DRAGGING';
export const SET_NEW_PIXEL_SIZE = 'SET_NEW_PIXEL_SIZE';
export const RESIZE_BOARD = 'RESIZE_BOARD';
export const SELECT_COLOR = 'SELECT_COLOR';
export const CLOSE_COLOR_PICKER = 'CLOSE_COLOR_PICKER';
export const TOGGLE_DISPLAY_COLOR_PICKER = 'TOGGLE_DISPLAY_COLOR_PICKER';
export const SET_WINDOW_SIZE = 'SET_WINDOW_SIZE';
